name: gautam
favicon: null
layout_spectrum: 0.6075461213476956
typography_spectrum: 0.9282721083145589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41846559825353324
  lightness: 0.7241558125242591
  saturation: 0.5390773974359035
  rhythmicContrast: 0.4909770009107888
purpose: []
